[package]
name = "lox1"
version = "0.1.0"
authors = ["Yosef Deray <yosefderay770@gmail.com>"]

[dependencies]

[lib]
name = "lox1"
path = "src/lib.rs"

[[bin]]
name = "lox1exec"

[[bin]]
name = "try_ast_print"
